project:
  type: website

format:
  html:
    theme:
        light: flatly
        dark: darkly
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    title: false
    background: primary
    left:
      - text: "PedroAI Blog"
        href: blog/index.qmd
    right:
      - text: "Stream"
        icon: twitch
        href: https://www.twitch.tv/pedroaitm


metadata-files: [
  nbdev.yml,
#  sidebar.yml,
]