project:
  type: website

format:
  html:
    theme:
        light: flatly
        dark: darkly
    css: styles.css
    toc: true

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  favicon: favicon.png
  navbar:
    title: false
    logo: logo.png
    logo-href: /blog
    background: primary
    left:
      - text: "PedroAI Blog"
        href: blog/index.qmd
    right:
      - text: "Stream"
        icon: twitch
        href: https://www.twitch.tv/pedroaitm
      - text: "Discord"
        icon: discord
        href: https://discord.gg/2AGH4cEAYC
      - text: "Twitter"
        icon: twitter
        href: https://twitter.com/pedro_aitm


metadata-files: [nbdev.yml]