# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/tmblog/',
                'doc_host': 'https://trackmania-ai.github.io',
                'git_url': 'https://github.com/trackmania-ai/tmblog/',
                'lib_path': 'tmblog'},
  'syms': {}}